name: hkf
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.12.2
  - blinker=1.6.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - click=8.1.7
  - flask=3.0.0
  - importlib-metadata=6.8.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libsqlite=3.43.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.3
  - markupsafe=2.1.3
  - ncurses=6.4
  - numpy=1.26.0
  - openssl=3.1.4
  - pandas=2.1.2
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - soupsieve=2.5
  - tk=8.6.13
  - tzdata=2023c
  - urllib3=2.0.7
  - werkzeug=3.0.1
  - wheel=0.41.2
  - xz=5.2.6
  - zipp=3.17.0
  - pip:
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - idna==3.6
      - requests==2.31.0
